# Generated by Django 3.1.4 on 2021-01-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilogram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumname_image',
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
